### ISSUE TITLE
Running `sky-pages new` inside an existing SKY Pages project gives message from out-skyux2

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/sky-pages-cli#29]
Running `sky-pages new` in a folder that is already a SKY Pages project results in the following text:

```
What is the root directory for your SPA? (example: my-spa-name) info: sky-pages-out-skyux2: Unknown command new
```

The CLI should prevent the `new` command from being passed to sky-pages-out-skyux2 so this message isn't displayed.

**Comment by Blackbaud-BobbyEarl** [comment]
This was also solved in #44 .
