### ISSUE TITLE
Investigate .nvmrc as a way to enforce specific Node version in SPA projects

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/sky-pages-cli#31]
We currently specify the minimum version of Node in our README, but it would be nice if we could enforce it in the actual project.  The `.nvmrc` config file might allow us to do that.

https://github.com/creationix/nvm#nvmrc

**Comment by Blackbaud-BobbyEarl** [comment]
Internally we use nvm as it allows for rapid testing in other version of node as well as better handling of global permissions.  If we do use the .nvmrc file, we should also document the requirement of nvm.

Perhaps as an alternative we could use https://docs.npmjs.com/files/package.json#engines

**Comment by Blackbaud-BobbyEarl** [comment]
Closing now that all three referenced above have been approved and merged.
